TIS-740/select quay multiple times
entur/enki pull request #1503
Opened 2024-08-28 08:34 UTC by solita-sabinaf

2024-08-28 09:06 UTC, solita-sabinaf commented on src/ext/JourneyPatternStopPointMap/JourneyPatternStopPointMap.tsx
> +  quayStopPointIndexesRecord: Record<string, number[]>;
Rename

2024-08-28 09:08 UTC, solita-sabinaf commented on src/ext/JourneyPatternStopPointMap/Quay/QuayMarker.tsx
> +        <QuayIndexTooltip
Rename

2024-08-28 09:15 UTC, solita-sabinaf commented on src/ext/JourneyPatternStopPointMap/Quay/QuayPositionChips.tsx
> +            <ConfirmDialog
Rethink this

2024-08-28 09:16 UTC, solita-sabinaf commented on src/i18n/translations/en.ts
> +  quayPosition: 'Position',
Rename

2024-08-29 10:33 UTC, solita-sabinaf commented on src/ext/JourneyPatternStopPointMap/JourneyPatternStopPointMap.tsx
> +  quayStopPointIndexesRecord: Record<string, number[]>;
I btw checked, both indices and indexes are valid 😄 Thought to keep as indexes so it's faster to recognise

2024-08-30 18:51 UTC, testower requested changes

2024-08-30 18:51 UTC, testower commented on src/i18n/translations/nb.ts
> +  quayOrder: 'Rekkefølgen',
```suggestion
  quayOrder: 'Rekkefølge',
```

2024-09-02 10:15 UTC, merged